In [10]:
import pandas as pd
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

from tensorflow.keras import layers

In [2]:
df=pd.read_csv('update_data_for_ann_by_removing_negative_value.csv')

In [3]:
df

,name,calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent
0,Seasoned Goldfish Crackers,30929.55,1567.03,574.28,795.34,60932.46,3567.04,142.65,21.66,620.05
1,Seasoned Goldfish Crackers,30928.70,1566.05,579.12,793.68,60933.55,3560.85,145.28,20.06,622.74
2,Seasoned Goldfish Crackers,30935.97,1559.81,572.48,791.48,60931.93,3565.40,150.28,17.00,617.10
3,Seasoned Goldfish Crackers,30928.59,1562.37,575.96,794.59,60934.70,3567.84,148.08,12.75,618.39
4,Seasoned Goldfish Crackers,30934.20,1565.55,578.72,799.75,60931.73,3559.95,151.82,18.15,614.34
...,...,...,...,...,...,...,...,...,...,...
999995,Beets in Sour Cream,106.08,9.27,0.00,15.45,259.37,12.61,2.95,14.42,0.00
999996,Beets in Sour Cream,109.99,3.36,2.15,15.49,260.99,15.11,1.57,12.35,0.52
999997,Beets in Sour Cream,109.48,10.34,0.00,19.78,262.54,11.99,0.00,13.48,1.20
999998,Beets in Sour Cream,109.24,8.48,0.00,11.44,262.94,11.88,0.00,6.58,0.00
999999,Beets in Sour Cream,104.12,5.55,0.00,17.49,257.49,14.99,0.00,5.43,2.52

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train_encoder=encoder.fit_transform(df['name'])

In [25]:
df['label_name']=y_train_encoder

In [27]:
df[['name','label_name']]

                              name  label_name
0       Seasoned Goldfish Crackers       15943
1       Seasoned Goldfish Crackers       15943
2       Seasoned Goldfish Crackers       15943
3       Seasoned Goldfish Crackers       15943
4       Seasoned Goldfish Crackers       15943
...                            ...         ...
999995         Beets in Sour Cream        1863
999996         Beets in Sour Cream        1863
999997         Beets in Sour Cream        1863
999998         Beets in Sour Cream        1863
999999         Beets in Sour Cream        1863

[1000000 rows x 2 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('name',axis=1),df['name'],test_size=0.2,random_state=42)

In [7]:
x_train

,calories,FatContent,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent
566853,262.12,18.05,6.96,10.57,185.25,29.79,1.72,19.94,0.39
382311,351.32,16.45,12.63,51.74,158.10,41.75,2.23,29.18,5.33
241519,450.10,19.88,4.80,48.53,1121.91,13.41,9.42,3.11,47.24
719220,203.15,13.16,6.50,18.50,111.08,31.54,5.22,20.23,5.84
905718,144.69,4.50,0.48,83.76,142.12,25.81,0.00,17.79,8.24
...,...,...,...,...,...,...,...,...,...
259178,433.84,9.03,0.97,243.92,1359.33,54.76,5.05,5.69,37.12
365838,357.73,16.43,5.10,163.63,274.78,22.48,4.17,14.70,30.10
131932,581.26,32.75,13.57,78.08,222.03,75.39,7.19,56.25,16.24
671155,215.66,3.41,4.30,29.10,224.20,40.19,0.00,37.19,0.00
121958,606.45,9.51,3.50,13.44,509.72,109.30,8.03,31.98,15.68

In [8]:
scaler=StandardScaler()
scaler.fit(x_train)
x_train_scaled=scaler.transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [16]:
model = Sequential()
model.add(Flatten(input_shape=(x_train.shape[1],)))
model.add(Dense(20000,activation='relu')),
model.add(Dense(2000,activation='relu'))
model.add(Dense(20000,activation='softmax'))

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 flatten_1 (Flatten)         (None, 9)                 0

 dense_3 (Dense)             (None, 20000)             200000

 dense_4 (Dense)             (None, 2000)              40002000

 dense_5 (Dense)             (None, 20000)             40020000

=================================================================
Total params: 80222000 (306.02 MB)
Trainable params: 80222000 (306.02 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),optimizer='Adam',metrics=['accuracy'])

NameError: name 'tf' is not defined

In [22]:
history=model.fit(x_train_scaled,y_train,epochs=100,validation_split=0.2,batch_size=50,verbose=1)

Epoch 1/100

UnimplementedError: Graph execution error:

Detected at node Cast_1 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\krishna\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start

  File "C:\Users\krishna\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start

  File "C:\Users\krishna\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever

  File "C:\Users\krishna\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once

  File "C:\Users\krishna\anaconda3\Lib\asyncio\events.py", line 80, in _run

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute

  File "C:\Users\krishna\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes

  File "C:\Users\krishna\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code

  File "C:\Users\krishna\AppData\Local\Temp\ipykernel_15760\1616064984.py", line 1, in <module>

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1783, in fit

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1377, in train_function

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1360, in step_function

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1349, in run_step

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1131, in train_step

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1225, in compute_metrics

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 620, in update_state

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\utils\metrics_utils.py", line 77, in decorated

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 140, in update_state_fn

  File "C:\Users\krishna\anaconda3\Lib\site-packages\keras\src\metrics\base_metric.py", line 708, in update_state

Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_2397]